name = "AntibodyPackagesRegistry"
uuid = "a8912519-5d54-48e3-8ca1-bd7204ec4833"
repo = "https://github.com/AntibodyPackages/AntibodyPackagesRegistry"
description = "AntibodyPackagesRegistry"

[packages]
36c19c45-0400-424e-9d0d-5bf8b8cd730c = { name = "AdaptiveDensityApproximationRecipes", path = "A/AdaptiveDensityApproximationRecipes" }
56a9bb0d-c37d-45c9-8e6c-6c1c1baae5c6 = { name = "AdaptiveDensityApproximation", path = "A/AdaptiveDensityApproximation" }
935aaf18-14c7-4785-87e9-38cf17c1e7c1 = { name = "FittingObjectiveFunctions", path = "F/FittingObjectiveFunctions" }
